<a href="https://colab.research.google.com/github/shivannadm/Data_Science_path/blob/main/01_Basic_python_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1)write a python program to handle missing data in a dataset replace the missing values with the mean of the respective column<pre>
import pandas as pd
import numpy as np
data = {
    'A': [10,np.nan,30,40],
    'B': [np.nan, 2, 3, 4],
    'C': [1, np.nan, np.nan, 4]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df.fillna(df.mean(),inplace=True)

print("\n after replacing  missing values:")
print(df)</pre>

out put:<pre>
Original DataFrame:
      A    B    C
0  10.0  NaN  1.0
1   NaN  2.0  NaN
2  30.0  3.0  NaN
3  40.0  4.0  4.0

 after replacing  missing values:
           A    B    C
0  10.000000  3.0  1.0
1  26.666667  2.0  2.5
2  30.000000  3.0  2.5
3  40.000000  4.0  4.0</pre>

2)write a python program to remove duplicate rows in a dataset<pre>
import pandas as pd
data = {
    'Name': ['Arjun', 'Bob', 'Abhi', 'David', 'Bob'],
    'Age': [21, 30, 21, 40, 30],
    'City': ['bengaluru','New York', 'hoskote','Chicago', 'New York']

}


df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_no_duplicates = df.drop_duplicates()

print("\n DataFrame after removing duplicate rows:")
print(df_no_duplicates)

out put:-
Original DataFrame:
    Name  Age       City
0  Arjun   21  bengaluru
1    Bob   30   New York
2   Abhi   21    hoskote
3  David   40    Chicago
4    Bob   30   New York

 DataFrame after removing duplicate rows:
    Name  Age       City
0  Arjun   21  bengaluru
1    Bob   30   New York
2   Abhi   21    hoskote
3  David   40    Chicago</pre>

3)write a python program to detect and remove outliers from a dataset using the z- score method<pre>
import pandas as pd
import numpy as np
data = {
    'A': [10,12,12, 13, 12, 100, 12, 14, 11, 12],
    'B': [15, 16, 15, 15, 20, 22, 21, 17, 15, 16],
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
def remove_outliers(df):
    z_scores = np.abs((df - df.mean()) / df.std())
    threshold = 2
    return df[(z_scores < threshold).all(axis=1)]
df_no_outliers = remove_outliers(df)

print("\nDataFrame after removing outliers:")
print(df_no_outliers)
<code>output:-</code>
Original DataFrame:
     A   B
0   10  15
1   12  16
2   12  15
3   13  15
4   12  20
5  100  22
6   12  21
7   14  17
8   11  15
9   12  16

DataFrame after removing outliers:
    A   B
0  10  15
1  12  16
2  12  15
3  13  15
4  12  20
6  12  21
7  14  17
8  11  15
9  12  16</pre>

4)write a python program to convert categorical data into numerical data using one hot encoding
<pre>
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago'],
    'Gender': ['Female', 'Male', 'Male', 'Male']
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_encoded = pd.get_dummies(df, columns=['City', 'Gender'], drop_first=True)

print("\nDataFrame after one-hot encoding:")
print(df_encoded)

<code>output:-</code>
Original DataFrame:
      Name         City  Gender
0    Alice     New York  Female
1      Bob  Los Angeles    Male
2  Charlie     New York    Male
3    David      Chicago    Male

DataFrame after one-hot encoding:
      Name  City_Los Angeles  City_New York  Gender_Male
0    Alice             False           True        False
1      Bob              True          False         True
2  Charlie             False           True         True
3    David             False          False         True</pre>

5) write a python program to normalize numerical data using min max normalization
<pre>
import pandas as pd

data = {
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45],
    'C': [100, 200, 300, 400, 500]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

def min_max_normalize(df):
    return (df - df.min()) / (df.max() - df.min())

df_normalized = min_max_normalize(df)

print("\nDataFrame after min-max normalization:")
print(df_normalized)

output:-
Original DataFrame:
    A   B    C
0  10   5  100
1  20  15  200
2  30  25  300
3  40  35  400
4  50  45  500

DataFrame after min-max normalization:
      A     B     C
0  0.00  0.00  0.00
1  0.25  0.25  0.25
2  0.50  0.50  0.50
3  0.75  0.75  0.75
4  1.00  1.00  1.00</pre>

6)write a python program to clean text data by removing special characters and converting all text to lowercase<pre>
import pandas as pd

data = {
    'text': [
        "Hello World!!!",
        "Python is awesome!!! @2023",
        "Let's clean this text, shall we? #NLP",
        "Special characters: @#$$%^&*()",
        "No special characters here."
    ]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

def clean_text(text):
    cleaned_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    cleaned_text = cleaned_text.lower()
    return cleaned_text

df['cleaned_text'] = df['text'].apply(clean_text)

print("\nDataFrame after cleaning text:")
print(df[['text', 'cleaned_text']])
<code>output:-</code>
Original DataFrame:
                                    text
0                         Hello World!!!
1             Python is awesome!!! @2023
2  Let's clean this text, shall we? #NLP
3         Special characters: @#$$%^&*()
4            No special characters here.

DataFrame after cleaning text:
                                    text                       cleaned_text
0                         Hello World!!!                        hello world
1             Python is awesome!!! @2023             python is awesome 2023
2  Let's clean this text, shall we? #NLP  lets clean this text shall we nlp
3         Special characters: @#$$%^&*()                special characters
4            No special characters here.         no special characters here</pre>